### PR TITLE
Update examples

### LINKED ISSUE #494: nix-shell after following the quickstart guide returns an error
## Expected Behavior

Following the [quickstart guide](https://digga.divnix.com/start/index.html) execute `nix-shell` to enter the interactive shell with all the dependencies

## Current Behavior

After following the [quickstart guide](https://digga.divnix.com/start/index.html), executing `nix-shell` returns an error saying it cannot coerce builtins.path into a string.

This patch solves the issue:
```diff
$ git diff lib/compat/default.nix
diff --git a/lib/compat/default.nix b/lib/compat/default.nix
index fc1bc0c..51c427c 100644
--- a/lib/compat/default.nix
+++ b/lib/compat/default.nix
@@ -1,8 +1,8 @@
 let
-  lock = builtins.fromJSON (builtins.readFile builtins.path {
+  lock = builtins.fromJSON (builtins.readFile (builtins.path {
     path = ../../flake.lock;
     name = "lockPath";
-  });
+  }));
   flake =
     import
     (
```

## Steps to Reproduce

1. Download [Nixos ISO](https://channels.nixos.org/nixos-22.11/latest-nixos-plasma5-x86_64-linux.iso) and install the system.
2. Follow the [quickstart guide](https://digga.divnix.com/start/index.html) to the end.
3. Execute `nix-shell`, you get the issue

## Your Environment

```console
[elhodred@arcadia:~/code/personal/dotfiles]$ nix run nixpkgs#nix-info -- -m; nix flake metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 22.11 (Raccoon), 22.11.968.9d692a724e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

warning: Git tree '/home/elhodred/code/personal/dotfiles' is dirty
Resolved URL:  git+file:///home/elhodred/code/personal/dotfiles
Locked URL:    git+file:///home/elhodred/code/personal/dotfiles
Description:   A highly structured configuration database.
Path:          /nix/store/6r64lda4fnfh3b3gq1h0d4f1cdd5vigg-source
Last modified: 2022-12-18 16:26:03
Inputs:
├───agenix: github:ryantm/agenix/a630400067c6d03c9b3e0455347dc8559db14288
│   └───nixpkgs follows input 'nixos'
├───darwin: github:LnL7/nix-darwin/adb8ac0453c8b2c40f5bffb578453dbaee838952
│   └───nixpkgs follows input 'nixpkgs-darwin-stable'
├───deploy: github:serokell/deploy-rs/2a3c5f70eee04a465aa534d8bd4fcc9bb3c4a8ce
│   ├───flake-compat: github:edolstra/flake-compat/64a525ee38886ab9028e6f61790de0832aa3ef03
│   ├───nixpkgs follows input 'nixos'
│   └───utils: github:numtide/flake-utils/0f8662f1319ad6abf89b3380dd2722369fc51ade
├───digga: github:divnix/digga/54ede8e591d288c176a09d6fcf4b123896c0bf0f
│   ├───darwin: github:LnL7/nix-darwin/2f2bdf658d2b79bada78dc914af99c53cad37cba
│   │   └───nixpkgs follows input 'digga/nixpkgs'
│   ├───deploy follows input 'deploy'
│   ├───devshell: github:numtide/devshell/899ca4629020592a13a46783587f6e674179d1db
│   │   ├───flake-utils: github:numtide/flake-utils/846b2ae0fc4cc943637d3d1def4454213e203cba
│   │   └───nixpkgs follows input 'digga/nixpkgs'
│   ├───flake-compat: github:edolstra/flake-compat/b4a34015c698c7793d592d66adbab377907a2be8
│   ├───flake-utils-plus: github:gytis-ivaskevicius/flake-utils-plus/6271cf3842ff9c8a9af9e3508c547f86bc77d199
│   │   └───flake-utils: github:numtide/flake-utils/3cecb5b042f7f209c56ffd8371b2711a290ec797
│   ├───home-manager follows input 'home'
│   ├───nixlib follows input 'nixos'
│   ├───nixpkgs follows input 'nixos'
│   └───nixpkgs-unstable: github:nixos/nixpkgs/3bacde6273b09a21a8ccfba15586fb165078fb62
├───flake-compat: github:edolstra/flake-compat/009399224d5e398d03b22badca40a37ac85412a1
├───home: github:nix-community/home-manager/6639e3a837fc5deb6f99554072789724997bc8e5
│   └───nixpkgs follows input 'nixos'
├───latest: github:nixos/nixpkgs/40f79f003b6377bd2f4ed4027dde1f8f922995dd
├───naersk: github:nmattia/naersk/d998160d6a076cfe8f9741e56aeec7e267e3e114
│   └───nixpkgs follows input 'nixos'
├───nixos: github:nixos/nixpkgs/5cb48ea3c19ce2e5746a44d6b91847396bd28c1f
├───nixos-generators: github:nix-community/nixos-generators/64a96ca8621d03cb3889daf0d3ff58d8209e3e0c
│   ├───nixlib: github:nix-community/nixpkgs.lib/28a5b0557f14124608db68d3ee1f77e9329e9dd5
│   └───nixpkgs: github:NixOS/nixpkgs/7fad01d9d5a3f82081c00fb57918d64145dc904c
├───nixos-hardware: github:nixos/nixos-hardware/e462a4baf75eeac639b4942481759de08a3bc94e
├───nixpkgs: github:NixOS/nixpkgs/80c24eeb9ff46aa99617844d0c4168659e35175f
├───nixpkgs-darwin-stable: github:NixOS/nixpkgs/ed5c42ecc8991ec52067f18d18e4aaaaeda8ac58
├───nur: github:nix-community/NUR/ccf9b872a81ec4ba8f79fd8e6c0b6f87a2548c20
└───nvfetcher: github:berberman/nvfetcher/294826951113dcd3aa9abbcacfb1aa5b95a19116
    ├───flake-compat: github:edolstra/flake-compat/b4a34015c698c7793d592d66adbab377907a2be8
    ├───flake-utils: github:numtide/flake-utils/6ee9ebb6b1ee695d2cacc4faa053a7b9baa76817
    └───nixpkgs follows input 'nixos'
```

### PR DESCRIPTION
**Pull request by Lord-Valen**
Resolves #494

### CODE REVIEW

**Comment by Lord-Valen** [comment]
CI is currently failing due to poetry lacking a security patch in 22.11. It should pass after NixOS/nixpkgs#206127 is merged.

**Comment by blaggacao** [comment]
Nice! I recently had to revert to python39 or so because of that, I guess.

**Comment by Lord-Valen** [comment]
The current failure is not isolated to this PR, as it is present in others. I ran checks on main and discovered the same failure.  This failure seems to be related to upstream changes in deploy-rs?

The lock-fileless approach to the examples seems to be problematic since a passing CI can silently become a failing CI. I imagine the motivation was for users to get the latest revisions of inputs when they use the template but we could instead instruct them to `nix flake update`. If they encounter issues related to updated inputs then that's something we should know about up front, rather than discovering it while making unrelated changes.

**Comment by Lord-Valen** [comment]
> This failure seems to be related to upstream changes in deploy-rs?

That seems to be the issue. I deleted the line `digga.inputs.deploy.follows = 'deploy';` and checks pass.

**Comment by Lord-Valen** [comment]
It seems that maybe deploy-rs does not support i686. I added an input for flake-utils, whose defaultSystems no longer include i686-linux and checks pass.

**Comment by blaggacao** [comment]
Are you on matrix? I'd have a couple of question regarding your expertise with `nixt`.

**Comment by Lord-Valen** [comment]
> Are you on matrix? I'd have a couple of question regarding your expertise with `nixt`.

I am `@lord-valen`.

**Comment by Lord-Valen** [comment]
> The lock-fileless approach to the examples seems to be problematic since a passing CI can silently become a failing CI. I imagine the motivation was for users to get the latest revisions of inputs when they use the template but we could instead instruct them to `nix flake update`. If they encounter issues related to updated inputs then that's something we should know about up front, rather than discovering it while making unrelated changes.

We can cover this in a follow-up PR. LGTM

**Comment by blaggacao** [comment]
Thank you! Merged on the basis of passing checks.

**Pull request merged**
