### PR TITLE
Revert devshell subflakification

### LINKED ISSUE #443: "Check & Cachix" workflow failing on `main`
## Expected Behavior
The "Check & Cachix" workflow should pass on the `main` branch.

## Current Behavior
The "Check & Cachix" workflow is failing with the following error in `nix develop --command evalnix`:

```
error: flake 'git+file:///home/runner/work/digga/digga' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

## Possible Solution
5b33c4baefe44379b80592fbf531304ff3b513b7 appears to have introduced the change.

I'm not entirely sure what the preferred solution should be. But for the time being I would recommend reverting the commit that introduced the issues and submit it as a pull request, ensuring that builds pass before merging.

## Steps to Reproduce
https://github.com/divnix/digga/runs/5668623763?check_suite_focus=true

## Context
I'm unable to work on #438 since rebasing onto `main`.

### PR DESCRIPTION
**Pull request by montchr**
Recent changes to `main` moved the devshell to a separate flake in a subdirectory. This caused numerous issues, initially on `main` but especially on #438 and Darwin hosts. It also broke `nix develop` unexpectedly by requiring the user specify the new path to the devshell flake as `./devshell#default`, which was not documented.

### Context

- #443 
- Discussion in 5b33c4baefe44379b80592fbf531304ff3b513b7
- Conversation in Matrix channel [[link](https://matrix.to/#/!luwEFvTJxfOhBlnMbr:myrdd.info/$4HW3Q7GMYibs2YOQre5_o0I5muQ1MqNrHxQl6I0Hf2w?via=matrix.org&via=pub.solar&via=myrdd.info)]

### Details

This PR reverts the following commits:

- 5b33c4baefe44379b80592fbf531304ff3b513b7
- 85496bd4deb2392c2abb27f889c0a090967ad8ff
- 94cc51e2b795780f5b44f89e9c3f06d5debf898a
- 75c0f266f46e0a3d110cec5b146c0ee48393cd2f
- 9da3840a6f4c86c3058f8bd2e1d824dbee2abdfe

### CODE REVIEW

**Comment by blaggacao** [comment]
Sorry, solved on `main`. `rg` always spares the `.dotfiles`... :grin:

**Comment by Pacman99** [comment]
Re-opening, I still want to revert the subflake changes, @montchr could you rebase and also revert the later fixup commits
The subflake changes shouldn't be in main without a PR in the first place

**Comment by Pacman99** [comment]
bors try

**Comment by montchr** [comment]
bors retry

**Comment by montchr** [comment]
bors try-

**Comment by montchr** [comment]
bors ping

**Comment by montchr** [comment]
bors try

**Comment by Pacman99** [comment]
Just force pushed to this branch to rebase on CI changes

**Pull request merged**
