### PR TITLE
ref: add proper downstream testing

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
:hourglass_flowing_sand:

**Comment by blaggacao** [comment]
bors try

**Comment by nrdxp** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try-

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Pull request merged**
