### PR TITLE
Make this repository digga

### PR DESCRIPTION
**Pull request by Pacman99**
closes: #430

This is just some git hacking to preserve both project's commit histories.

Commands that I ran:
```sh
git remote add digga git@github.com:divnix/digga
git checkout -b digga-main digga/main
git checkout -b merge-digga upstream/main
mkdir ../devos
mv * .editorconfig .envrc .gitignore ../devos/
mkdir examples
mv ../devos examples/
git add . && git commit -m "tree: move everything into examples/devos"
git checkout digga-main
git rebase merge-digga # there were 3 merge conflicts with src/pkgs-lib/shell, not sure why but that file has been deleted so I just delt with them
git checkout merge-digga
git merge digga-main --ff-only
git push upstream merge-digga
```
There are a lot of changes, so it'll be easier to review what exactly I did with git to get it this way.

The only actual changes I personally made:
 - removed .gitmodules and downstream submodule
 - move devos into examples/devos
 - removed bud template from devos and added `devos` template to digga

This doesn't cover devos docs, I think we will need a separate effort to merge devos docs into digga docs. Probably as a digga usage section or something. For now devos docs are just sitting in `examples/devos`.

This PR should theoretically have the same amount of commits being added as the number of commits in digga itself. I think it ended up being around 50 less because bors commits aren't included for some reason.

### CODE REVIEW

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
> I can try tomorrow to do a git filter-repo merge of two unrelated histories whereby the devos history lands entirely in examples/devos, albeit all commits will be rewritten with the new subdir prefix.
> 
> Then, I can replay the manual changes that you did on top.

I don't think that's a good idea because it would rewrite this repos git history which is never good for public branches.  It would make sense if were merging devos into digga, but not when were doing it this way.

**Comment by blaggacao** [comment]
Ah! I see. i think I got lost first pass replaying your steps in my head. I then came ubder the impression commit history was lost, even if you explicitly stated otherwise. :shrug:

**Comment by blaggacao** [comment]
bors r+

In this case rather wake up with a unified Digga/DevOS.

Thank you!

**Pull request merged**
