### PR TITLE
Update to latest follows fix patch sha

### PR DESCRIPTION
**Pull request by teutat3s**
Tested and Devos `flake.lock` works on latest `nixos` channel with this new patch sha.

### CODE REVIEW

**Review by GTrunSec — APPROVED** [review]

**Comment by Pacman99** [comment]
I think we have to update the nix source too, so the patch applies cleanly

**Comment by teutat3s** [comment]
> I think we have to update the nix source too, so the patch applies cleanly

Where would I do that? In the `flake.lock` file?

**Comment by Pacman99** [comment]
I think bumping nixpkgs should be enough, lets see
bors try

**Comment by teutat3s** [comment]
It seems this was already fixed via 2c5953f284690a89bfd472418141e3afea2dcf5d, feel free to re-open otherwise.

**Pull request closed without merging**
