### PR TITLE
fix deploy-rs multi-arch

### PR DESCRIPTION
**Pull request by GTrunSec**
Regarding https://github.com/divnix/digga/issues/18.

### CODE REVIEW

**Review by blaggacao — APPROVED** [review]
LGTM. @Pacman99 any objections?

**Comment by blaggacao** [comment]
bors try

**Comment by Pacman99** [comment]
LGTM I just changed the base branch to `develop`. I would consider adding multi-arch support a new feature. 

I just fixed the conflicts and force pushed to your branch.

bors r+

**Review by Pacman99 — APPROVED** [review]
bors r+

**Review by Pacman99 — APPROVED** [review]
bors r+

**Comment by Pacman99** [comment]
Ok done, thank you for the PR!

**Pull request merged**
