### PR TITLE
rename current modules -> exportedModules

### PR DESCRIPTION
**Pull request by Pacman99**
and externalModules -> modules

supersedes #103

### CODE REVIEW

**Comment by Pacman99** [comment]
The deprecation strategy here is just to error out if `externalModules` is used at all. There is no way to do any sort of "soft" deprecation scheme, because the renames overlap so in the module system trying to switch options will cause infinite recursion.

**Review by blaggacao — APPROVED** [review]

**Comment by blaggacao** [comment]
bord r+

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
merging based on earlier approval and successful bors run

**Pull request merged**
