### PR TITLE
da/refactor tests

### PR DESCRIPTION
**Pull request by blaggacao**
##### ~~TODO: update ci~~

1. mv fullFlake -> example
1. add groupByConfig example
1. ref: auxiliaries (checks, jobs, devshell)
1. fix classicalDevos example
1. fmt
1. evalnix
1. ref: ci to new shift-left testing strategy | please do TDD form now on

### CODE REVIEW

**Comment by blaggacao** [comment]
```console
[general commands]

  evalnix              - Check Nix parsing
  fmt                  - Check Nix formatting
  menu                 - prints this menu
  rm-locks             - Remove all lock files

[tests]

  check-all            - Checks all example
  check-classicalDevos - Checks classicalDevos example
  check-groupByConfig  - Checks groupByConfig example
```

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
Upstream fix for the test failure: https://github.com/NixOS/nixpkgs/pull/127628

**Comment by GTrunSec** [comment]
> same error as you experienced

Thanks a lot.

**Comment by blaggacao** [comment]
bors try

[backport has been merged](https://github.com/NixOS/nixpkgs/pull/127720) and since the examples don't pin a lock file on purpose, this should now work (or expose a different error)

**Review by nrdxp — APPROVED** [review]
Did a fairly brief review but it if it improves testing I'm all for it. There doesn't seem to be anything obviously wrong. LGTM
bors r+

**Pull request merged**
